project:
  type: website
  output-dir: docs

website:
  title: "Josh Stim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - example_analysis.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    
editor: visual



